# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ChristianFilipina' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChristianFilipina
  rn_path = '../node_modules/react-native'
  
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  ]
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  
  pod 'RNIap', :path => '../node_modules/react-native-iap'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == "React"
              target.remove_from_project
          end
      end
  end
  

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'


end

target 'ChristianFilipina-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    
end

target 'ChristianFilipinaTests' do
    inherit! :search_paths
    # Pods for testing
end
